services:
  - type: web
    runtime: node
    name: nptel-affective-computing
    plan: free
    buildCommand: npm install && npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOSTNAME
        value: 0.0.0.0
