services:
  - type: web
    runtime: node
    name: nptel-affective-computing
    plan: free
    nodeVersion: "20"
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
